version: "3.0"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8081:8081"
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
volumes:
  amir-jenkins:
  sonar-conf:
  sonar-data:
  sonar-logs:
  sonar-extensions:
